import React, { useState } from "react";
import { Form, ActionPanel, Action, showToast, Toast, Clipboard } from "@raycast/api";

export default function Command() {
  const [hours, setHours] = useState<string>("12");
  const [rate, setRate] = useState<string>("75");
  const [client, setClient] = useState<string>("Client Enterprise LLC");
  const [features, setFeatures] = useState<string>("Custom OAuth Integration, Export to Excel, Webhook alerts");

  const totalBleed = (parseFloat(hours) || 0) * (parseFloat(rate) || 0);

  async function handleSubmit() {
    const report = `# SCOPE CREEP AUDIT & REVENUE RECOVERY REPORT
Generated by ScopeLock AI

Client: ${client}
Scope Exposure: ${hours} hours @ $${rate}/hr
Total Unbilled Value Bleed: $${totalBleed.toFixed(2)} USD

Out-of-Scope Items Detected:
${features.split(",").map(f => `- ${f.trim()}`).join("\n")}

LEGAL REMEDY:
Under statutory UCC § 2-209, these items cannot be absorbed without written amendment.
To issue court-admissible change order:
👉 Patreon Gateway: https://patreon.com/c/scopelock
👉 Payoneer Clearance: ahirwardhanmanti83@gmail.com`;

    await Clipboard.copy(report);
    await showToast({
      style: Toast.Style.Success,
      title: `Scope Bleed: $${totalBleed.toFixed(2)}`,
      message: "Full Recovery Report copied to clipboard!"
    });
  }

  return (
    <Form
      actions={
        <ActionPanel>
          <Action.SubmitForm title="Copy Legal Audit Report" onSubmit={handleSubmit} />
          <Action.OpenInBrowser title="Unlock Commercial Enforceability ($2)" url="https://patreon.com/c/scopelock" />
        </ActionPanel>
      }
    >
      <Form.TextField id="client" title="Client Name" value={client} onChange={setClient} />
      <Form.TextArea id="features" title="Unscoped Feature Requests" value={features} onChange={setFeatures} />
      <Form.TextField id="hours" title="Estimated Unbilled Hours" value={hours} onChange={setHours} />
      <Form.TextField id="rate" title="Hourly Rate ($/hr)" value={rate} onChange={setRate} />
      <Form.Description title="Calculated Revenue Loss" text={`⚠️ $${totalBleed.toFixed(2)} USD currently uncollected`} />
    </Form>
  );
}
